#!/usr/bin/env node

var fs = require('file-system');

class BadArgsError extends Error {
  constructor () {
    super('// TODO: Make this message better');
  }
}

class SemanticVersion {
  constructor(version) {
    this.versionText = version;
    let parts = version.split('.');
    if (parts.length === 3) {
      this.isSemVer = true;
      this.patch = parts[2];
      this.patch = parts[1];
  
      if (isNaN(parts[0][0])) {
        this.major = parts[0].slice(1);
        this.pin = parts[0][0];
      } else {
        this.major = parts[0];
      }
    }
  }

  toString () {
    return this.versionText;
  }
}

/**************************************************************************
 * USAGE:     clone-lite [github url] [file1] [file2] [file3] [...] 
 *************************************************************************/

const sync = require('child_process').spawnSync;

function parseURL(url) {
  let parts = url.split("/");
  let version = new SemanticVersion('master');
  let name = parts[parts.length -1];
  if (name.includes('#')) {
    let parts = name.split('#');
    name = parts[0];
    version = new SemanticVersion(parts[1]);
    url = url.replace('#' + parts[1],'');
  }

  return {
    name: name.replace('.git', ''),
    url: url.replace('.git', '').replace('https://github.com','https://api.github.com/repos'),
    version: version
  }
}

function interpolateArgs () {
  if (process.argv.length < 3) {
    throw new BadArgsError();
  }

  let args = process.argv.slice(0); // deep clone

  // TODO make this more inuitive to user mix ups
  let urlData = parseURL(args[2]);
  return {
    repoName: urlData.name,
    getURL: urlData.url,
    version: urlData.version,
    files: args.slice(3)
  }
}


function get(file, url, dir, version) {
  let formattedURL = `${url}/contents/${file}?ref=${version.toString()}&access_token=${process.env.GITHUB_AUTH_TOKEN}`;
  console.log(`clone-lite\t\t\t${url.replace('api.github.com/repos','github.com')}/${file}#${version.toString()}`);
  sync('curl', [
    '-o', `${dir}/${file}`,
    formattedURL
  ])
  expandFileContents(`${dir}/${file}`);
}

function expandFileContents (filePath) {
  let json = JSON.parse(sync('cat', [filePath]).stdout.toString());
  if (json.encoding && json.content) {
    let fileContents = new Buffer(json.content, json.encoding).toString()
    fs.writeFileSync(filePath, fileContents);
  } else {
    console.warn(filePath, 'Could not be expanded.')
  }
}

function mkdir(name) {
  console.log("MKDIR: ",  name);
  sync('mkdir', [name])
}




function main () {
  const repo = interpolateArgs();
  mkdir(repo.repoName);
  repo.files.forEach(file => {
    get(file, repo.getURL, repo.repoName, repo.version);
  });
}

main();